config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  get 'dashboard/index'
  get 'shifts/edit_schedule', to: 'shifts#edit_schedule', as: 'edit_schedule'
  get 'shifts/export_excel', to: 'shifts#export_excel', defaults: { format: :xlsx }, as: 'export_excel'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'inquiry', to: 'static_pages#inquiry'
  post 'shifts/create_schedule', to: 'shifts#create_schedule', as: 'create_schedule'
  patch 'shifts/update_schedule', to: 'shifts#update_schedule', as: 'update_schedule'
  delete 'shifts/destroy_all', to: 'shifts#destroy_all', as: 'destroy_all_shifts'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "tops#index"
  resources :users, only: %i[new create] 
  resources :employees
  resources :shifts, only: %i[index new create edit update]
  resources :shift_requests, only: %i[new create destroy]
  resources :memos, only: [:create]
  resources :contacts, only: [:new, :create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
  default_scope { order(:position) }
  validates :name, presence: true
  validates :employee_type, inclusion: { in: %w[正社員 パート 派遣] }

  belongs_to :user
  has_many :shifts, dependent: :destroy
  has_many :shift_requests, dependent: :destroy

  validate :at_least_one_shift_selected

  private

  def at_least_one_shift_selected
    unless early_shift || day_shift || late_shift || night_shift
      errors.add(:base, "1つ以上シフトを選択してください")
    end
  end
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  belongs_to :shift, optional: true
  
  validates :date, presence: true
  validates :content, presence: true, allow_blank: true # 空白の内容を許容
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :employee
  belongs_to :user
  has_many :memos, dependent: :destroy
  has_many :shift_requests, dependent: :destroy

  validates :date, presence: true
  validates :shift_type, presence: true
end

app/models/shift_request.rb
class ShiftRequest < ApplicationRecord
  belongs_to :employee
  belongs_to :user
  belongs_to :shift, optional: true

  validates :date, presence: true
  validates :shift_type, presence: true, inclusion: { in: %w[早番 日勤 遅番 夜勤 休み], allow_blank: true }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true

  has_many :shifts
  has_many :employees
  has_many :shift_requests
  has_many :memos
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @employees = current_user.employees
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def create
    @memo = current_user.memos.new(memo_params)
    @memo.save
    redirect_to new_shift_path(year: params[:memo][:year], month: params[:memo][:month])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :require_login, only: %i[index]

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: 'ユーザー登録が完了しました'
    else
      flash[:danger] = 'ユーザー登録に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_design(type)
    case type.to_sym
    when :success then "bg-blue bg-opacity-20 text-gray rouded px-8 py-5"
    when :danger then "bg-beige text-gray rouded px-8 py-5"
    else "bg-gray"
    end
  end

  def page_title(title = '')
    base_title = 'Care Shift'
    title.present? ? "#{title} | #{base_title}" : base_title
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<% content_for(:title, 'スタッフ管理') %>
<body class="flex flex-col h-screen">
  <%= render 'layouts/header' %>
  <div class="flex flex-1 overflow-hidden">
    <!-- Sidebar -->
    <%= render 'layouts/employee_sidebar' %>
    <!-- Main Content -->
    <main class="flex-1">
      <%= render 'layouts/flash_messages' %>
      <div class="staff-container">
        <div class="staff-title justify-between flex p-4">
          <div class="text-2xl text-black ml-4">スタッフ表</div>
          <%= link_to new_employee_path, class: "btn btn-sm border-gray border-opacity-50 bg-white text-gray rounded hover:bg-blue hover:text-white hover:border-blue px-7 ml-auto mr-8" do %>
            スタッフ追加
          <% end %>
        </div>
      </div>
      <div class="max-w-6xl h-full">
        <div class="overflow-y-auto pl-8 h-144">
          <% if @employees.any? %>
            <table class="table table-fixed border-separate border-spacing-0">
              <!-- head -->
              <thead>
                <tr class="sticky top-0 z-10 bg-white">
                  <th class="border border-b-4 border-gray-100 text-center text-black text-base">名前</th>
                  <th class="border border-b-4 border-gray-100 text-center text-black text-base">雇用形態</th>
                  <th class="border border-b-4 border-gray-100 text-center text-black text-base">勤務可能シフト</th>
                  <th class="border border-b-4 border-gray-100 text-center text-black text-base"></th>
                </tr>
              </thead>
              <tbody id="sortable-table-body" data-controller="sortable">
                <% @employees.each do |employee| %>
                  <tr class="hover:bg-whitesmoke">
                    <td class="border border-gray-100 text-center text-gray text-base font-semibold"><%= employee.name %></td>
                    <% if employee.employee_type == '正社員' %>
                      <td class="border border-gray-100 text-center text-blue text-base font-semibold"><%= employee.employee_type %></td>
                    <% elsif employee.employee_type == 'パート' %>
                      <td class="border border-gray-100 text-center text-soft-green text-base font-semibold"><%= employee.employee_type %></td>
                    <% else %>
                      <td class="border border-gray-100 text-center text-gray text-base font-semibold"><%= employee.employee_type %></td>
                    <% end %>
                    <td class="border border-gray-100 text-center text-gray text-base">
                      <div class="flex justify-center border-b-0">
                        <% if employee.early_shift %>
                          <div class="bg-blue text-white text-sm p-1 m-1 rounded-md border-b-0">早番</div>
                        <% end %>
                        <% if employee.day_shift %>
                          <div class="bg-soft-green text-white text-sm p-1 m-1 rounded-md border-b-0">日勤</div>
                        <% end %>
                        <% if employee.late_shift %>
                          <div class="bg-gray text-white text-sm p-1 m-1 rounded-md border-b-0">遅番</div>
                        <% end %>
                        <% if employee.night_shift %>
                          <div class="bg-black text-white text-sm p-1 m-1 rounded-md border-b-0">夜勤</div>
                        <% end %>
                      </div>
                    </td>
                    <td class="border border-gray-100 text-center text-gray text-base">
                      <div class="flex justify-center border-b-0">
                        <%= link_to edit_employee_path(employee), class: "btn btn-sm btn-ghost text-blue hover:bg-gray-100 rounded-sm mx-1" do %>
                          <img class="p-0" src="/images/edit.svg" alt=""><span>編集</span>
                        <% end %>
                        <%= link_to employee, data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' } , class: "btn btn-sm btn-ghost text-red hover:bg-gray-100 rounded-sm mx-1" do %>
                          <img class="inline-block m-0 p-0" src="/images/delete.svg" alt=""><span>削除</span>
                        <% end %>
                      </div>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <div class="flex justify-center items-center h-screen">
              <div class="text-xl text-gray">スタッフを追加してください</div>
            </div>
          <% end %>
        </div>
      </div>
    </main>
  </div>
</body>