config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  get 'dashboard/index'
  get 'shifts/edit_schedule', to: 'shifts#edit_schedule', as: 'edit_schedule'
  get 'shifts/export_excel', to: 'shifts#export_excel', defaults: { format: :xlsx }, as: 'export_excel'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'inquiry', to: 'static_pages#inquiry'
  post 'shifts/create_schedule', to: 'shifts#create_schedule', as: 'create_schedule'
  patch 'shifts/update_schedule', to: 'shifts#update_schedule', as: 'update_schedule'
  delete 'shifts/destroy_all', to: 'shifts#destroy_all', as: 'destroy_all_shifts'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "tops#index"
  resources :users, only: %i[new create] 
  resources :employees
  resources :shifts, only: %i[index new create edit update]
  resources :shift_requests, only: %i[new create destroy]
  resources :memos, only: [:create]
  resources :contacts, only: [:new, :create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :employee
  belongs_to :user
  has_many :memos, dependent: :destroy
  has_many :shift_requests, dependent: :destroy

  validates :date, presence: true
  validates :shift_type, presence: true
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  skip_before_action :require_login, only: [:create_schedule]
  skip_before_action :verify_authenticity_token, only: [:create_schedule]

  def index
    Rails.logger.debug "Calling set_month_data in ShiftsController#index"
    set_month_data(params[:year], params[:month])
    
    # current_userに関連する従業員を取得
    @employees = current_user.employees

    # current_userに関連するシフトデータを取得
    @shifts = Shift.where(employee_id: @employees.pluck(:id)).group_by(&:employee_id)

    # current_userに関連するメモを取得
    @memos = Memo.where(date: @start_date..@end_date, user_id: current_user.id).index_by(&:date)
    
    @shift_counts = sum_shift_counts(@employees, @shifts, @calendar)
  end

  def new
    @year = params[:year]
    @month = params[:month]

    set_month_data(@year, @month)

    # current_userに関連する従業員を取得
    @employees = current_user.employees

    # current_userに関連するシフトリクエストを取得
    @shift_requests = ShiftRequest.where(date: @start_date..@end_date, user_id: current_user.id).group_by(&:employee_id)
    
    # current_userに関連するメモを取得
    @memos = Memo.where(date: @start_date..@end_date, user_id: current_user.id).index_by(&:date)
  end

  def edit
    set_month_data(params[:year], params[:month])
    @schedule_output = @schedule_output || {}
  end

  def update_schedule
    set_month_data(params[:year], params[:month])

    # current_userに関連する従業員を取得
    @employees = current_user.employees

    @schedule_output = @schedule_output || {}

    # current_userに関連するメモを取得
    @memos = Memo.where(date: @start_date..@end_date, user_id: current_user.id).index_by(&:date)

    # current_userに関連するシフトデータを取得
    @shifts = Shift.where(date: @start_date..@end_date, employee_id: @employees.pluck(:id)).group_by(&:employee_id)
    
    ActiveRecord::Base.transaction do
      params[:shifts].each do |employee_id, shifts|
        shifts.each do |date, shift_type|
          formatted_shift_type = format_shift_type(shift_type)
          shift = Shift.find_or_initialize_by(employee_id: employee_id, date: date)
          shift.shift_type = formatted_shift_type
          unless shift.save
            flash[:danger] = 'シフトの保存に失敗しました'
            raise ActiveRecord::Rollback
          end
        end
      end
    
      params[:memos].each do |date, content|
        memo = Memo.find_by(date: date, user_id: current_user.id)
        if content.blank?
          memo&.destroy
        else
          memo ||= Memo.new(date: date, user: current_user)
          memo.content = content
          unless memo.save
            flash[:danger] = 'メモの保存に失敗しました'
            raise ActiveRecord::Rollback
          end
        end
      end
    end
    
    flash[:success] = 'シフトを変更しました'
    redirect_to shifts_path(year: params[:year], month: params[:month])
  end  

  def create
    params[:shifts].each do |shift_params|
      shift = Shift.new(shift_params.permit(:date, :shift_type, :employee_id))
      shift.user = current_user
      unless shift.save
        flash[:danger] = 'シフトの保存に失敗しました'
      end
    end
    flash[:success] = 'シフトを保存しました'
    redirect_to shifts_path
  end

  def create_schedule
    Rails.logger.debug "Calling set_month_data in ShiftsController#create_schedule"
    set_month_data(params[:year], params[:month]) 
    
    # current_userに関連する従業員を取得
    @employees = current_user.employees

    # current_userに関連するメモを取得
    @memos = Memo.where(date: @start_date..@end_date, user_id: current_user.id).index_by(&:date)

    employees = current_user.employees
    dates = (@start_date..@end_date).to_a
    shift_requests = ShiftRequest.where(date: @start_date..@end_date, user_id: current_user.id).group_by(&:employee_id)

    data = {
      employees: employees.map do |e|
        shifts = {}
        shifts[:early_shift] = e.early_shift if e.early_shift
        shifts[:day_shift] = e.day_shift if e.day_shift
        shifts[:late_shift] = e.late_shift if e.late_shift
        shifts[:night_shift] = e.night_shift if e.night_shift
        {
          id: e.id,
          name: e.name,
          employee_type: e.employee_type,
          shift_requests: shift_requests[e.id]&.map { |sr| { date: sr.date.to_s, shift_type: sr.shift_type } } || []
        }.merge(shifts)
      end,
      dates: dates.map(&:to_s)
    }

    Rails.logger.info "Data for Python script: #{data.inspect}"
    json_data = data.to_json

    output = IO.popen("python3 #{Rails.root.join('lib', 'shift_test.py')}", "r+") do |f|
      f.puts json_data
      f.close_write
      f.read
    end

    Rails.logger.info "Python script output: #{output}"

    begin
      parsed_output = JSON.parse(output)
      if parsed_output.key?("Error")
        clear_shift_requests_and_memos(@start_date, @end_date)
        flash[:danger] = 'シフトを作成できませんでした。勤務希望を再度調整してください。またはスタッフを追加してください'
        redirect_to new_shift_request_path(year: params[:year], month: params[:month]) and return
      end
      @schedule_output = parsed_output.empty? ? {}: parsed_output
    rescue JSON::ParserError => e
      Rails.logger.error "JSON Parse Error: #{e.message}"
      Rails.logger.error "Failed output: #{output}"
      @schedule_output = {}
    end

    Rails.logger.info "Parsed schedule output: #{@schedule_output.inspect}"

    flash.now[:success] = 'シフトを作成しました'
    render :edit, status: :unprocessable_entity
  end

  def edit_schedule
    set_month_data(params[:year], params[:month])

    # current_userに関連する従業員を取得
    @employees = current_user.employees

    # current_userに関連するメモを取得
    @memos = Memo.where(date: @start_date..@end_date, user_id: current_user.id).index_by(&:date)

    # current_userに関連するシフトデータを取得
    @shifts = Shift.where(date: @start_date..@end_date, employee_id: @employees.pluck(:id)).group_by(&:employee_id)
    @shifts.default = [] 
  end

  def destroy_all
    start_date = Date.new(params[:year].to_i, params[:month].to_i, 1)
    end_date = start_date.end_of_month

    ActiveRecord::Base.transaction do
      # current_userに関連するシフトを削除
      Shift.where(date: start_date..end_date, employee_id: current_user.employees.pluck(:id)).destroy_all
      
      # current_userに関連するシフトリクエストを削除
      ShiftRequest.where(date: start_date..end_date, user_id: current_user.id).destroy_all
      
      # current_userに関連するメモを削除
      Memo.where(date: start_date..end_date, user_id: current_user.id).destroy_all
    end

    redirect_to shifts_path(year: params[:year], month: params[:month]), success: 'シフトを削除しました'
  rescue ActiveRecord::RecordNotDestroyed => e
    redirect_to shifts_path(year: params[:year], month: params[:month]), alert: "削除に失敗しました: #{e.message}"
  end

  def export_excel
    set_month_data(params[:year], params[:month])

    # current_userに関連する従業員を取得
    @employees = current_user.employees

    # current_userに関連するシフトデータを取得
    @shifts = Shift.where(date: @start_date..@end_date, employee_id: @employees.pluck(:id)).group_by(&:employee_id)

    # current_userに関連するメモを取得
    @memos = Memo.where(date: @start_date..@end_date, user_id: current_user.id).index_by(&:date)
  
    respond_to do |format|
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename=shifts_#{params[:year]}_#{params[:month]}.xlsx"
      }
    end
  end

  private

  def shift_params
    params.require(:shift).permit(:date, :shift_type, :employee_id)
  end

  def sum_shift_counts(employees, shifts, calendar)
    counts = {}
    employees.each do |employee|
      counts[employee.id] = { early: 0, day: 0, late: 0, night: 0, off: 0 }
      calendar.each do |date|
        next unless shifts[employee.id]
        shift = shifts[employee.id].find { |s| s.date == date }
        next unless shift
        case shift.shift_type
        when "早番"
          counts[employee.id][:early] += 1
        when "日勤"
          counts[employee.id][:day] += 1
        when "遅番"
          counts[employee.id][:late] += 1
        when "夜勤"
          counts[employee.id][:night] += 1
        when "休み"
          counts[employee.id][:off] += 1
        end
      end
    end
    counts
  end

  def format_shift_type(shift_type)
    case shift_type
    when 'H' then '早番'
    when 'N' then '日勤'
    when 'O' then '遅番'
    when 'Y' then '夜勤'
    when '明け' then '夜勤明け'
    when '⚫️' then '休み'
    else shift_type
    end
  end

  def clear_shift_requests_and_memos(start_date, end_date)
    ShiftRequest.where(date: start_date..end_date, user_id: current_user.id).destroy_all
    Memo.where(date: start_date..end_date, user_id: current_user.id).destroy_all
  end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/edit_schedule.html.erb
<% content_for(:title, 'シフト編集') %>
<body class="flex flex-col h-screen">
  <%= render 'layouts/header' %>
  <div class="flex flex-1 overflow-hidden">
    <!-- Sidebar -->
    <%= render 'layouts/shift_sidebar' %>
    <main class="flex-1">
      <%= render 'layouts/flash_messages' %>
      <%= form_with url: update_schedule_path(year: @year, month: @month), method: :patch, local: true do |form| %>
        <div class="flex justify-between">
          <div class="flex items-center">
            <h1 class="text-xl font-semibold text-gray ml-6 mt-4">シフト編集</h1>
          </div>
          <div class="flex">
            <%= form.hidden_field :year, value: @year %>
            <%= form.hidden_field :month, value: @month %>
            <%= form.submit 'シフトを変更する', class: "btn btn-sm border-gray border-opacity-50 bg-white text-gray rounded hover:bg-blue hover:text-white hover:border-blue px-7 ml-auto mt-4 mr-2" %>
            <%= link_to "戻る", shifts_path, class: "btn btn-sm border-gray border-opacity-50 bg-white text-gray rounded hover:bg-blue hover:text-white hover:border-blue px-2 ml-auto mt-4 mr-6" %>
          </div>
        </div>
        <div class="max-w-6xl h-144 mr-4 my-3 mx-6 overflow-y-auto overflow-auto">
          <table class="table-fixed w-full border-separate border-spacing-0">
            <thead>
              <tr>
                <th class="p-1 w-40 sticky left-0 z-20 bg-white border-r border-gray-100"></th>
                <% @calendar.each do |c| %>
                  <td class="border border-gray-100 p-1 w-12 text-gray text-center sticky top-0 z-10 bg-white font-semibold">
                    <%= "#{c.month}/#{c.day}" %>
                  </td>
                <% end %>
              </tr>
            </thead>
            <thead>
              <tr>
                <th class="p-1 sticky left-0 z-20 bg-white border-r border-gray-100"></th>
                <% @calendar.each do |c| %>
                  <% if c.wday == 0 %>
                    <td class="border border-gray-100 p-1 text-red text-center sticky top-8 z-10 bg-white font-semibold">
                      <%= @weeks[c.wday] %>
                    </td>
                  <% elsif c.wday == 6 %>
                    <td class="border border-gray-100 p-1 text-blue text-center sticky top-8 z-10 bg-white font-semibold">
                      <%= @weeks[c.wday] %>
                    </td>
                  <% else %>
                    <td class="border border-gray-100 text-gray p-1 text-center sticky top-8 z-10 bg-white font-semibold">
                      <%= @weeks[c.wday] %>
                    </td>
                  <% end %>
                <% end %>
              </tr>
            </thead>
            <thead>
              <tr>
                <th class="sticky left-0 z-20 bg-white border border-gray-100 text-center text-gray py-10">委員会 <br> 予定 <br> 行事</th>
                <% @calendar.each do |c| %>
                  <td class="border border-gray-100 p-2">
                    <%= form.text_area "memos[#{c}]", class: "vertical-textarea text-gray text-sm", value: @memos[c]&.content %>
                  </td>
                <% end %>
              </tr>
            </thead>
            <% @employees.each do |e| %>
            <thead>
              <tr>
                <% if e.employee_type == '正社員' %>
                  <th class="sticky left-0 z-20 bg-white border border-gray-100 p-2 text-center text-blue"><%= e.name %></th>
                <% elsif e.employee_type == 'パート' %>
                  <th class="sticky left-0 z-20 bg-white border border-gray-100 p-2 text-center text-soft-green"><%= e.name %></th>
                <% else %>
                  <th class="sticky left-0 z-20 bg-white border border-gray-100 p-2 text-center text-gray"><%= e.name %></th>
                <% end %>
                <% @calendar.each do |c| %>
                <td class="border border-gray-100 p-2 text-center">
                  <% if @shifts[e.id] %>
                    <% shift = @shifts[e.id].find { |s| s.date == c } %>
                    <% current_shift = case shift&.shift_type
                       when "早番" then "H"
                       when "日勤" then "N"
                       when "遅番" then "O"
                       when "夜勤" then "Y"
                       when "夜勤明け" then "明け"
                       when "休み" then "⚫️"
                       else ""
                       end %>
                    <%= form.select "shifts[#{e.id}][#{c}]",
                        [["", ""], ["H", "H"], ["N", "N"], ["O", "O"], ["Y", "Y"], ["明け", "明け"], ["⚫️", "⚫️"]],
                        { selected: current_shift },
                        class: "text-xs w-full p-0"
                    %>
                  <% end %>
                </td>
                <% end %>
              </tr>
            </thead>
            <% end %>
          </table>
        </div>
      <% end %>
    </main>
  </div>
</body>

app/views/shifts/index.html.erb
<% content_for(:title, 'シフト管理') %>
<body class="flex flex-col h-screen">
  <%= render 'layouts/header' %>
  <div class="flex flex-1 overflow-hidden">
    <!-- Sidebar -->
    <%= render 'layouts/shift_sidebar' %>
    <% if @employees.any? %>
      <main class="flex-1">
        <%= render 'layouts/flash_messages' %>
        <div class="flex justify-between">
          <div class="flex items-center">
            <%= link_to shifts_path(year: @start_date.prev_month.year, month: @start_date.prev_month.month), class: "btn btn-sm border-gray border-opacity-50 bg-white text-gray rounded hover:bg-blue hover:border-blue ml-6 mt-4 p-0 group" do %>
              <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor" class="group-hover:text-white">
                <path d="M560-240 320-480l240-240 56 56-184 184 184 184-56 56Z"/>
              </svg>
            <% end %>
            <h1 class="mt-4 ml-2 text-xl text-gray"><%= @shift_calendar %></h1>
            <%= link_to shifts_path(year: @start_date.next_month.year, month: @start_date.next_month.month), class: "btn btn-sm border-gray border-opacity-50 bg-white text-gray rounded hover:bg-blue hover:border-blue ml-2  mt-4 p-0 group" do %>
              <svg xmlns="http://www.w3.org/2000/svg" height="22px" viewBox="0 -960 960 960" width="24px" fill="currentColor" class="group-hover:text-white">
                <path d="M504-480 320-664l56-56 240 240-240 240-56-56 184-184Z"/>
              </svg>
            <% end %>
          </div>
          <% if @shifts.values.flatten.select { |shift| shift.date.year == @year.to_i && shift.date.month == @month.to_i }.any? %>
            <div class="flex">
              <%= link_to 'Excelに出力', export_excel_path(year: @year, month: @month, format: :xlsx), class: "btn btn-sm border-gray border-opacity-50 bg-white text-gray rounded hover:bg-blue hover:text-white hover:border-blue px-7 ml-auto mt-4 mr-4" %>
              <%= link_to edit_schedule_path(year: @year, month: @month), class: "mt-4 mr-2 hover:bg-whitesmoke rounded" do %>
                <svg xmlns="http://www.w3.org/2000/svg" height="30px" viewBox="0 -960 960 960" width="30px" fill="#13b5ea">
                  <path d="M186.67-120q-27 0-46.84-19.83Q120-159.67 120-186.67v-586.66q0-27 19.83-46.84Q159.67-840 186.67-840h389L509-773.33H186.67v586.66h586.66v-324.66L840-578v391.33q0 27-19.83 46.84Q800.33-120 773.33-120H186.67ZM480-480ZM360-360v-170l377-377q10-10 22.33-14.67 12.34-4.66 24.67-4.66 12.67 0 25.04 5 12.38 5 22.63 15l74 75q9.4 9.97 14.53 22.02 5.13 12.05 5.13 24.51 0 12.47-4.83 24.97-4.83 12.5-14.83 22.5L530-360H360Zm499-424.67-74.67-74.66L859-784.67Zm-432.33 358H502l246-246L710-710l-38.33-37.33-245 244.33v76.33ZM710-710l-38.33-37.33L710-710l38 37.33L710-710Z"/>
                </svg>
              <% end %>
              <%= link_to destroy_all_shifts_path(year: @year, month: @month), data: { turbo_method: :delete, turbo_confirm: 'シフトを削除しますか？' }, class: "mr-6 mt-4 hover:bg-whitesmoke rounded" do %>
              <svg xmlns="http://www.w3.org/2000/svg" height="30px" viewBox="0 -960 960 960" width="30px" fill="#FF6969">
                <path d="M261-120q-24.75 0-42.37-17.63Q201-155.25 201-180v-570h-41v-60h188v-30h264v30h188v60h-41v570q0 24-18 42t-42 18H261Zm438-630H261v570h438v-570ZM367-266h60v-399h-60v399Zm166 0h60v-399h-60v399ZM261-750v570-570Z"/>
              </svg>
              <% end %>
            </div>
          <% else %>
            <%= form_with url: new_shift_request_path, method: :get, local: true do |form| %>
              <%= form.hidden_field :year, value: @year %>
              <%= form.hidden_field :month, value: @month %>
              <%= form.submit '勤務希望を入力する', class: "btn btn-sm border-gray border-opacity-50 bg-white text-gray rounded hover:bg-blue hover:text-white hover:border-blue px-7 ml-auto mt-4 mr-6" %>
            <% end %>
          <% end %>
        </div>
        <div class="max-w-6xl h-144  mr-4 my-3 mx-6 overflow-y-auto overflow-auto">
          <table class="table-fixed w-full border-separate border-spacing-0">
            <thead>
              <tr>
                <th class="p-1 w-40 sticky left-0 z-20 bg-white border-r border-gray-100"></th>
                <% @calendar.each do |c| %>
                  <td class="border border-gray-100 p-1 w-12 text-gray text-center sticky top-0 z-10 bg-white font-semibold">
                    <%= "#{c.month}/#{c.day}" %>
                  </td>
                <% end %>
                <td class="border border-gray-100 p-1 w-12 bg-white text-gray text-center sticky top-0 z-20">早番</td>
                <td class="border border-gray-100 p-1 w-12 bg-white text-gray text-center sticky top-0 z-20">日勤</td>
                <td class="border border-gray-100 p-1 w-12 bg-white text-gray text-center sticky top-0 z-20">遅番</td>
                <td class="border border-gray-100 p-1 w-12 bg-white text-gray text-center sticky top-0 z-20">夜勤</td>
                <td class="border border-gray-100 p-1 w-12 bg-white text-gray text-center sticky top-0 z-20">休み</td>
              </tr>
            </thead>
            <thead>
              <tr>
                <th class="p-1 sticky left-0 z-20 bg-white border-r border-gray-100"></th>
                <% @calendar.each do |c| %>
                  <% if c.wday == 0 %>
                    <td class="border border-gray-100 p-1 text-red text-center sticky top-8 z-10 bg-white font-semibold">
                      <%= @weeks[c.wday] %>
                    </td>
                  <% elsif c.wday == 6 %>
                    <td class="border border-gray-100 p-1 text-blue text-center sticky top-8 z-10 bg-white font-semibold">
                      <%= @weeks[c.wday] %>
                    </td>
                  <% else %>
                    <td class="border border-gray-100 text-gray p-1 text-center sticky top-8 z-10 bg-white font-semibold">
                      <%= @weeks[c.wday] %>
                    </td>
                  <% end %>
                <% end %>
                <td class="border border-gray-100 p-1 bg-white text-gray text-center sticky top-8"></td>
                <td class="border border-gray-100 p-1 bg-white text-gray text-center sticky top-8"></td>
                <td class="border border-gray-100 p-1 bg-white text-gray text-center sticky top-8"></td>
                <td class="border border-gray-100 p-1 bg-white text-gray text-center sticky top-8"></td>
                <td class="border border-gray-100 p-1 bg-white text-gray text-center sticky top-8"></td>
              </tr>
            </thead>
            <thead>
              <tr>
                <th class="sticky left-0 z-10 bg-white border border-gray-100 text-center text-gray py-10">委員会 <br> 予定 <br> 行事</th>
                <% @calendar.each do |c| %>
                  <td class="border border-gray-100 p-2 vertical-textarea text-gray text-sm">
                    <%= @memos[c]&.content %>
                  </td>
                <% end %>
                <td class="border border-gray-100 p-1 text-gray text-center"></td>
                <td class="border border-gray-100 p-1 text-gray text-center"></td>
                <td class="border border-gray-100 p-1 text-gray text-center"></td>
                <td class="border border-gray-100 p-1 text-gray text-center"></td>
                <td class="border border-gray-100 p-1 text-gray text-center"></td>
              </tr>
            </thead>
            <% @employees.each do |e| %>
            <thead>
              <tr>
                <% if e.employee_type == '正社員' %>
                  <th class="sticky left-0 z-20 bg-white border border-gray-100 p-2 text-center text-blue"><%= e.name %></th>
                <% elsif e.employee_type == 'パート' %>
                  <th class="sticky left-0 z-20 bg-white border border-gray-100 p-2 text-center text-soft-green"><%= e.name %></th>
                <% else %>
                  <th class="sticky left-0 z-20 bg-white border border-gray-100 p-2 text-center text-gray"><%= e.name %></th>
                <% end %>
                <% @calendar.each do |c| %>
                  <td class="border border-gray-100 p-2 text-center text-black">
                    <% if @shifts[e.id] %>
                      <% shift = @shifts[e.id].find { |s| s.date == c } %>
                      <% if shift %>
                        <% case shift.shift_type %>
                        <% when "早番" %>
                          H
                        <% when "日勤" %>
                          &nbsp; <!-- 空白にする -->
                        <% when "遅番" %>
                          O
                        <% when "夜勤", "夜勤明け" %>
                          Y
                        <% when "休み" %>
                          ⚫️
                        <% else %>
                          <%= shift.shift_type %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </td>
                <% end %>
                <td class="border border-gray-100 p-2 text-center text-black"><%= @shift_counts[e.id][:early] %></td>
                <td class="border border-gray-100 p-2 text-center text-black"><%= @shift_counts[e.id][:day] %></td>
                <td class="border border-gray-100 p-2 text-center text-black"><%= @shift_counts[e.id][:late] %></td>
                <td class="border border-gray-100 p-2 text-center text-black"><%= @shift_counts[e.id][:night] %></td>
                <td class="border border-gray-100 p-2 text-center text-black"><%= @shift_counts[e.id][:off] %></td>
              </tr>
            </thead>
            <% end %>
          </table>
        </div>
      </main>
    <% else %>
      <main class="flex-1">
        <div class="h-screen">
          <div class="flex justify-end">
          <%= link_to new_employee_path, class: "btn btn-sm border-gray border-opacity-50 bg-white text-gray rounded hover:bg-blue hover:text-white hover:border-blue px-7 ml-auto mr-8 mt-4" do %>
            スタッフ追加
          <% end %>
        </div>
          <div class="flex justify-center items-center h-144">
            <div class="text-xl text-gray">スタッフを追加してください</div>
          </div>
        </div>
      </main>
    <% end %>
  </div>
</body>

app/views/shifts/new.html.erb
<% content_for(:title, 'シフト作成') %>
<body class="flex flex-col h-screen">
  <%= render 'layouts/header' %>
  <div class="flex flex-1 overflow-hidden">
    <!-- Sidebar -->
    <%= render 'layouts/shift_sidebar' %>
    <main class="flex-1">
      <%= render 'layouts/flash_messages' %>
      <div class="flex justify-end">
        <%= form_with url: create_schedule_path, method: :post, local: true do |form| %>
          <%= form.hidden_field :year, value: @year %>
          <%= form.hidden_field :month, value: @month %>
          <%= form.submit 'シフト作成', class: "btn btn-sm border-gray border-opacity-50 bg-white text-gray rounded hover:bg-blue hover:text-white hover:border-blue px-7 ml-auto mt-4 mr-6" %>
        <% end %>
      </div>
      <div class="max-w-6xl h-144  mr-4 my-3 mx-6 overflow-y-auto overflow-auto">
        <table class="table-fixed w-full border-separate border-spacing-0">
          <thead>
            <tr>
              <th class="p-1 w-40 sticky left-0 z-20 bg-white border-r border-gray-100"></th>
              <% @calendar.each do |c| %>
                <td class="border border-gray-100 p-1 w-12 text-gray text-center sticky top-0 z-10 bg-white font-semibold">
                  <%= "#{c.month}/#{c.day}" %>
                </td>
              <% end %>
            </tr>
          </thead>
          <thead>
            <tr>
              <th class="p-1 sticky left-0 z-20 bg-white border-r border-gray-100"></th>
              <% @calendar.each do |c| %>
                <% if c.wday == 0 %>
                  <td class="border border-gray-100 p-1 text-red text-center sticky top-8 z-10 bg-white font-semibold">
                    <%= @weeks[c.wday] %>
                  </td>
                <% elsif c.wday == 6 %>
                  <td class="border border-gray-100 p-1 text-blue text-center sticky top-8 z-10 bg-white font-semibold">
                    <%= @weeks[c.wday] %>
                  </td>
                <% else %>
                  <td class="border border-gray-100 text-gray p-1 text-center sticky top-8 z-10 bg-white font-semibold">
                    <%= @weeks[c.wday] %>
                  </td>
                <% end %>
              <% end %>
            </tr>
          </thead>
          <thead>
            <tr>
              <th class="sticky left-0 z-20 bg-white border border-gray-100 text-center text-gray py-10">委員会 <br> 予定 <br> 行事</th>
              <% @calendar.each do |c| %>
              <td class="border border-gray-100 p-2 vertical-textarea text-gray">
                <%= @memos[c]&.content %>
              </td>
              <% end %>
            </tr>
          </thead>
          <% @employees.each do |e| %>
          <thead>
            <tr>
              <% if e.employee_type == '正社員' %>
                <th class="sticky left-0 z-20 bg-white border border-gray-100 p-2 text-center text-blue"><%= e.name %></th>
              <% elsif e.employee_type == 'パート' %>
                <th class="sticky left-0 z-20 bg-white border border-gray-100 p-2 text-center text-soft-green"><%= e.name %></th>
              <% else %>
                <th class="sticky left-0 z-20 bg-white border border-gray-100 p-2 text-center text-gray"><%= e.name %></th>
              <% end %>
              <% @calendar.each do |c| %>
              <td class="border border-gray-100 p-2 text-center text-black">
                <% shift_request = @shift_requests[e.id]&.find { |s| s.date == c } %>
                <%= shift_request ? format_display_shift_type(shift_request.shift_type) : '' %>
              </td>
              <% end %>
            </tr>
            </div>
          </thead>
          <% end %>
        </table>
      </div>
    </main>
  </div>
</body>