config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  get 'dashboard/index'
  get 'shifts/edit_schedule', to: 'shifts#edit_schedule', as: 'edit_schedule'
  get 'shifts/export_excel', to: 'shifts#export_excel', defaults: { format: :xlsx }, as: 'export_excel'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'inquiry', to: 'static_pages#inquiry'
  post 'shifts/create_schedule', to: 'shifts#create_schedule', as: 'create_schedule'
  patch 'shifts/update_schedule', to: 'shifts#update_schedule', as: 'update_schedule'
  delete 'shifts/destroy_all', to: 'shifts#destroy_all', as: 'destroy_all_shifts'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "tops#index"
  resources :users, only: %i[new create] 
  resources :employees
  resources :shifts, only: %i[index new create edit update]
  resources :shift_requests, only: %i[new create destroy]
  resources :memos, only: [:create]
  resources :contacts, only: [:new, :create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
  default_scope { order(:position) }
  validates :name, presence: true
  validates :employee_type, inclusion: { in: %w[正社員 パート 派遣] }

  belongs_to :user
  has_many :shifts, dependent: :destroy
  has_many :shift_requests, dependent: :destroy

  validate :at_least_one_shift_selected

  private

  def at_least_one_shift_selected
    unless early_shift || day_shift || late_shift || night_shift
      errors.add(:base, "1つ以上シフトを選択してください")
    end
  end
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  belongs_to :shift, optional: true
  
  validates :date, presence: true
  validates :content, presence: true, allow_blank: true # 空白の内容を許容
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :employee
  belongs_to :user
  has_many :memos, dependent: :destroy
  has_many :shift_requests, dependent: :destroy

  validates :date, presence: true
  validates :shift_type, presence: true
end

app/models/shift_request.rb
class ShiftRequest < ApplicationRecord
  belongs_to :employee
  belongs_to :user
  belongs_to :shift, optional: true

  validates :date, presence: true
  validates :shift_type, presence: true, inclusion: { in: %w[早番 日勤 遅番 夜勤 休み], allow_blank: true }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true

  has_many :shifts
  has_many :employees
  has_many :shift_requests
  has_many :memos
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def create
    @memo = current_user.memos.new(memo_params)
    @memo.save
    redirect_to new_shift_path(year: params[:memo][:year], month: params[:memo][:month])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :require_login, only: %i[index]

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: 'ユーザー登録が完了しました'
    else
      flash[:danger] = 'ユーザー登録に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_design(type)
    case type.to_sym
    when :success then "bg-blue bg-opacity-20 text-gray rouded px-8 py-5"
    when :danger then "bg-beige text-gray rouded px-8 py-5"
    else "bg-gray"
    end
  end

  def page_title(title = '')
    base_title = 'Care Shift'
    title.present? ? "#{title} | #{base_title}" : base_title
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_before_login_header.html.erb
<header class="shadow-sm">
  <div class="navbar bg-base-100">
    <div class="flex-1">
      <%= link_to root_path, class: "btn btn-ghost text-xl flex items-center font-mono text-black" do %>
      <span class="material-symbols-outlined">
        <svg xmlns="http://www.w3.org/2000/svg" height="48px" viewBox="0 -960 960 960" width="48px" fill="#434343"><path d="M180-80q-24 0-42-18t-18-42v-620q0-24 18-42t42-18h65v-60h65v60h340v-60h65v60h65q24 0 42 18t18 42v260h-60v-70H180v430h320v60H180Zm0-550h600v-130H180v130Zm0 0v-130 130ZM560-80v-123l221-220q9-9 20-13t22-4q12 0 23 4.5t20 13.5l37 37q9 9 13 20t4 22q0 11-4.5 22.5T902.09-300L683-80H560Zm300-263-37-37 37 37ZM620-140h38l121-122-18-19-19-18-122 121v38Zm141-141-19-18 37 37-18-19Z"/></svg>
      </span>
        Care Shift
      <% end %>
    </div>
    <div class="flex-none">
      <ul class="menu menu-horizontal px-1">
        <li class="mr-2">
          <%= link_to login_path, class: "btn border-blue bg-white text-gray rounded hover:bg-blue hover:text-white hover:border-blue px-7" do %>
          ログイン
          <% end %>
        </li>
        <li class="mr-2">
          <%= link_to new_user_path, class: "btn btn-primary px-7 text-white rounded hover:text-blue hover:bg-white" do %>
          新規登録
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_employee_sidebar.html.erb
<nav class="bg-white shadow-lg w-60 p-4 flex flex-col justify-between h-screen">
  <ul>
    <li class="mb-2">
      <%= link_to dashboard_index_path, class:"flex items-center text-sidebar bg-gray-100 p-2 rounded" do %>
        <img src="/images/person.svg" alt="person-icon" class="mr-2 w-6 h-6">
        スタッフ管理
      <% end %>
    </li>
    <li class="mb-2">
      <%= link_to shifts_path, class: "flex items-center text-sidebar hover:bg-gray-100 p-2 rounded" do %>
        <img src="/images/check-calendar.svg" alt="" class="mr-2 w-6 h-6">
        シフト管理
      <% end %>
    </li>
  </ul>
  <ul>
    <div class="border-t pb-4 border-gray border-opacity-30"></div>
    <li class="mb-2">
      <%= link_to new_contact_path, class: "flex items-center text-sidebar hover:bg-gray-100 p-2 rounded" do %>
        <img src="/images/help.svg" alt="" class="mr-2 w-6 h-6">
        お問い合わせ
      <% end %>
    </li>
    <li class="mb-2">
      <%= link_to inquiry_path, class: "flex items-center text-sidebar hover:bg-gray-100 p-2 rounded" do %>
        <img src="/images/service.svg" alt="" class="mr-2 w-6 h-6">
        利用規約
      <% end %>
    </li>
    <li class="mb-2">
      <%= link_to privacy_policy_path, class: "flex items-center text-sidebar hover:bg-gray-100 p-2 rounded" do %>
        <img src="/images/privacy.svg" alt="" class="mr-2 w-6 h-6">
        プライバシーポリシー
      <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="<%= flash_design(message_type) %> flex">
    <% if message_type.to_sym == :success %>
      <%= image_tag '/images/check.svg', alt: 'Check', class: 'pr-2' %> 
    <% else %>
      <%= image_tag '/images/close.svg', alt: 'Check', class: 'pr-2' %> 
    <% end %>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer footer-center p-10 rounded text-gray text-opacity-50">
  <nav class="grid grid-flow-col gap-4">
    <%= link_to '利用規約', inquiry_path, class: "link link-hover" %>
    <%= link_to 'プライバシーポリシー', privacy_policy_path, class: "link link-hover" %>
    <%= link_to 'お問い合わせ', new_contact_path, class: "link link-hover" %>
  </nav> 
  <aside>
    <p>Copyright © 2024 - Care Shift</p >
  </aside>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm border-b border-gray border-opacity-30">
  <div class="navbar bg-base-100">
    <div class="flex-1">
      <%= link_to root_path, class: "btn btn-ghost text-xl flex items-center font-mono text-black" do %>
      <span class="material-symbols-outlined">
        <svg xmlns="http://www.w3.org/2000/svg" height="48px" viewBox="0 -960 960 960" width="48px" fill="#434343"><path d="M180-80q-24 0-42-18t-18-42v-620q0-24 18-42t42-18h65v-60h65v60h340v-60h65v60h65q24 0 42 18t18 42v260h-60v-70H180v430h320v60H180Zm0-550h600v-130H180v130Zm0 0v-130 130ZM560-80v-123l221-220q9-9 20-13t22-4q12 0 23 4.5t20 13.5l37 37q9 9 13 20t4 22q0 11-4.5 22.5T902.09-300L683-80H560Zm300-263-37-37 37 37ZM620-140h38l121-122-18-19-19-18-122 121v38Zm141-141-19-18 37 37-18-19Z"/></svg>
      </span>
        Care Shift
      <% end %>
    </div>
    <div class="flex-none">
      <ul class="menu menu-horizontal">
        <li class="">
          <div class="w-16">
            <img src="/images/bell.svg" alt="">
          </div>
        </li>
        <li class="mr-2">
          <div class="flex-none p-0">
          <div class="dropdown dropdown-end">
            <div tabindex="0" role="button" class="btn btn-ghost">
              <div class="w-11 rounded-full hover:bg-blue hover:bg-opacity-30">
                <img alt="" src="/images/acount.svg" class="">
              </div>
            </div>
            <div tabindex="0" class="z-[1] card card-compact dropdown-content w-44 bg-whitesmoke shadow rounded-sm">
                <div class="card-body">
                  <%= link_to logout_path, class:"btn btn-ghost btn-sm text-black text-sm hover:text-soft-blue hover:bg-purple hover:bg-opacity-10 rounded-sm", data: { turbo_method: :delete } do %>
                    ログアウト
                  <% end %>
                </div>
              </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shift_sidebar.html.erb
<nav class="bg-white shadow-lg w-60 p-4 flex flex-col justify-between h-full">
  <ul>
    <li class="mb-2">
      <%= link_to dashboard_index_path, class:"flex items-center text-sidebar hover:bg-gray-100 p-2 rounded" do %>
        <img src="/images/person.svg" alt="" class="mr-2 w-6 h-6">
        スタッフ管理
      <% end %>
    </li>
    <li class="mb-2">
      <%= link_to shifts_path, class: "flex items-center text-sidebar bg-gray-100 p-2 rounded" do %>
      <img src="/images/check-calendar.svg" alt="" class="mr-2 w-6 h-6">
      シフト管理
    <% end %>
    </li>
  </ul>
  <ul>
    <div class="border-t pb-4 border-gray border-opacity-30"></div>
    <li class="mb-2">
      <%= link_to new_contact_path, class: "flex items-center text-sidebar hover:bg-gray-100 p-2 rounded" do %>
        <img src="/images/help.svg" alt="" class="mr-2 w-6 h-6">
        お問い合わせ
      <% end %>
    </li>
    <li class="mb-2">
      <%= link_to inquiry_path, class: "flex items-center text-sidebar hover:bg-gray-100 p-2 rounded" do %>
        <img src="/images/service.svg" alt="" class="mr-2 w-6 h-6">
        利用規約
      <% end %>
    </li>
    <li class="mb-2">
      <%= link_to privacy_policy_path, class: "flex items-center text-sidebar hover:bg-gray-100 p-2 rounded" do %>
        <img src="/images/privacy.svg" alt="" class="mr-2 w-6 h-6">
        プライバシーポリシー
      <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>